# Generated by Django 3.2.4 on 2021-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='open',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
