# Generated by Django 3.2.4 on 2021-06-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stocks_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='open',
            new_name='open_price',
        ),
    ]
